name: Version

on:
  push:
    branches: [ master ]

jobs:
  version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        git-user-name: 'Conventional Changelog Action'
        git-user-email: 'conventional_changelog@github.actions.com'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        release-count: '10'
        version-file: './manifest.json'
        version-path: 'version_number'
        skip-on-empty: 'true'
        skip-version-file: 'false'
        skip-commit: 'false'
    - name: Create Release
      uses: actions/create-release@v1
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
