name: CI

on:
  push:
    branches: [ master ]

jobs:
  version:
    runs-on: ubuntu-latest
    
    name: Calculate version
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}

    steps:
    - uses: actions/checkout@v2
    - name: Create Changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
        git-user-name: 'Conventional Changelog Action'
        git-user-email: 'conventional_changelog@github.actions.com'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        release-count: '10'
        version-file: './manifest.json'
        version-path: 'version_number'
        skip-on-empty: 'true'
        skip-version-file: 'false'
        skip-commit: 'false'

  build:
    runs-on: ubuntu-latest
        
    name: Publish
    needs: version    
    if: ${{ needs.version.outputs.skipped == 'false' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          
      - name: Setup Unity
        uses: kuler90/setup-unity@v1.0.6
        with:
          unity-version: 2019.4.20f1
        
      - name: Build and Create the package
        run: dotnet build ChestReloadedPlugin.sln -c Release
          
      - name: Zip
        run: |
          mkdir output
          cp Plugin/bin/Release output/plugins
      - uses: papeloto/action-zip@v1
        with:
          files: output/ icon.png manifest.json README.md
          dest: ChestReloaded_release.zip
          
      - name: Upload to NexusMods
        run: |
          unex upload 504 ChestReloaded_release.zip -v ${{ needs.version.outputs.tag }}
        env:
          UNEX_APIKEY: ${{ secrets.NEXUS_API_KEY }}
          UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
          UNEX_DEBUG: true
          UNEX_FILENAME: ChestReloaded
          UNEX_GAME: valheim

      - name: Create GH Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.version.outputs.tag }}
          name: Valheim Chest Reloaded ${{ needs.version.outputs.tag }}
          body: ${{ needs.version.outputs.clean_changelog }}
          artifacts: "ChestReloaded_release.zip"
          token: ${{ secrets.github_token }}
